version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "angular6-demo"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing docker
      - apt-get update
      - apt-get install -y apt-transport-https
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce

      - echo Pulling trion/ng-cli-e2e
      - docker pull trion/ng-cli-e2e

      - echo Installing yarn
      - npm install -g yarn
      - echo Installing source NPM dependencies...
      - yarn
      - yarn global add @angular/cli
  pre_build:
    commands:
      - npm run lint
      - docker container run -u $(id -u) --rm --mount src=`pwd`,target=/app,type=bind trion/ng-cli-e2e ng test --watch false --single-run true --code-coverage true --sourcemaps false
      - docker container run -u $(id -u) --rm --mount src=`pwd`,target=/app,type=bind trion/ng-cli-e2e ng e2e
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
