version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "angular6-demo"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing node
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - echo Pulling trion/ng-cli-e2e
      - docker pull trion/ng-cli-e2e
      - echo Installing yarn
      - npm install -g yarn
      - echo Installing source NPM dependencies...
      - yarn global add @angular/cli
  pre_build:
    commands:
      - yarn run lint
      - docker container run -u $(id -u) --rm --mount src=`pwd`,target=/app,type=bind trion/ng-cli-e2e rm -rf node_modules && npm install -g yarn && yarn
      - docker container run -u $(id -u) --rm --mount src=`pwd`,target=/app,type=bind trion/ng-cli-e2e ng test --watch false --progress false
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
