version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "angular6-demo"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing yarn
      - npm install -g yarn

      # https://aws.amazon.com/blogs/devops/how-to-run-headless-front-end-tests-with-aws-cloud9-and-aws-codebuild/
      - echo Installing chrome
      - yarn add --dev puppeteer @angular-devkit/build-angular
      - echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome | grep not
      - apt-get upgrade
      - apt-get update
      - apt-get install -y apt-transport-https
      - apt-get install -y libxcursor1
      - apt-get install -y libgtk-3-dev
      - apt-get install -y libxss1
      - apt-get install -y libasound2
      - apt-get install -y libnspr4
      - apt-get install -y libnss3
      - apt-get install -y libx11-xcb1
      - echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome | grep not

      - echo Installing source NPM dependencies...
      - yarn
      - yarn global add @angular/cli
  pre_build:
    commands:
      - npm run lint
      - ng test
      - ng e2e
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
