version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "angular6-demo"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo installing yarn
      - npm install -g yarn
      - echo Installing source NPM dependencies...
      - yarn
      - yarn global add @angular/cli tslint stylelint
  pre_build:
    commands:
      - tslint **/*.ts
  build:
    commands:
      - echo Build started on `date`
      - ng build --env=${BUILD_ENV}
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
